version: '3.8'

volumes:
  postgres_data:
    driver: local

services:
  money-lover-wallet-db:
    image: postgres:alpine
    ports:
      - "5431:5432"
    environment:
      POSTGRES_DB: money-lover-wallet
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root