CREATE TABLE wallets
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name     VARCHAR(255),
    balance  BIGINT,
    currency VARCHAR(255),
    CONSTRAINT pk_wallets PRIMARY KEY (id)
);